name: MyWorkflow file
on:
  push:
    branches: [main]

jobs:
  builds:
  # Create VR with Ubuntu OS
    runs-on: Ubuntu-20.04

    steps:
    # First step to say hello
      - name: greeting steps
        run:
          echo "Hello there"

      - name: Checkout my codes
        uses: actions/checkout@v4
      - name: print content
        run: |
          ls

      # This is where I install python
      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: check version of python
        run: |
          python --version
