name: MyWorkflow File
on:
  pull_request:
  push:
    branches: [main] 

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    - name: greeting steps
      run: |
        echo "Hello World"

    # This is where I checkout my code
    - name: Checkout my code
      uses: actions/checkout@v4
    - name: print content of Repo
      run: |
        ls
      

    # This is where I install python
    - name: Installing Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: check version of python
      run: |
        python --version

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Begin test
      run: |
        pytest 

    # This is where we access the hidden repo
    # - name: Checkout hidden repo
    #   uses: actions/checkout@v4
    #   with:
    #     repository: KevinTan1203/UOBHidden
    #     path: hiddenfolder
    #     token: ${{ secrets.SECRETUOB }}
            
    # This prints out a hidden file
    # - name: Print out hidden file
    #   run: |
    #     ls
    #     cd hiddenfolder
    #     ls

    - name: discord
      uses: sebastianpopp/discord-action@releases/v2
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: ${{ github.repository }} pending deployment...
   
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DEPLOY }}
        publish_dir: ./

    - if: ${{ success() }}
      name: discord
      uses: sebastianpopp/discord-action@releases/v2
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: "${{ github.repository }} is deployed and now live! Please go and view it at the link provided: https://kevintan1203.github.io/GitTest/"

    - if: ${{ failure() }}
      name: discord
      uses: sebastianpopp/discord-action@releases/v2
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: ${{ github.repository }} deployment failed!
